svn merge -r766:1220 https://scst.svn.sourceforge.net/svnroot/scst/trunk/scripts

diff --git a/branches/sysfs/scripts/blockdev-perftest b/branches/sysfs/scripts/blockdev-perftest
--- a/branches/sysfs/scripts/blockdev-perftest
+++ b/branches/sysfs/scripts/blockdev-perftest
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 ############################################################################
 #
@@ -26,18 +26,95 @@
 # Function definitions  #
 #########################
 
-function usage {
-  echo "Usage: $0 [-a] [-d] [-n] [-s <l2s>] <dev>"
+usage() {
+  echo "Usage: $0 [-a] [-d] [-f] [-i <i>] [-j] [-n] [-r] [-s <l2s>] [-t [user@]host] <dev>"
   echo "        -a - use asynchronous (buffered) I/O."
   echo "        -d - use direct (non-buffered) I/O."
+  echo "        -f - force -- skip the test if there is still data present."
+  echo "        -i - number times each test is iterated."
+  echo "        -j - use fio instead of dd for benchmarking."
   echo "        -n - do not verify the data on <dev> before overwriting it."
+  echo "        -r - only perform the read test."
   echo "        -s - logarithm base two of the I/O size."
+  echo "        -t - username and hostname of the target to drop the caches on."
   echo "        <dev> - block device to run the I/O performance test on."
 }
 
-function drop_caches {
+# Compute two raised to the power $1.
+pow2() {
+  if [ $1 = 0 ]; then
+    echo 1
+  else
+    echo $((2 * $(pow2 $(($1 - 1)) ) ))
+  fi
+}
+
+# Report via the exit status whether or not the current user has sufficient
+# privileges to drop the VM caches.
+can_drop_cache() {
+  [ -w /proc/sys/vm/drop_caches ]
+}
+
+drop_caches() {
   sync
-  echo 3 > /proc/sys/vm/drop_caches
+  if can_drop_cache; then
+    echo 3 > /proc/sys/vm/drop_caches
+  fi
+  if [ "${target_login}" != "" ]; then
+    ssh -n ${target_login} 'sync; if [ -w /proc/sys/vm/drop_caches ]; then echo 3 > /proc/sys/vm/drop_caches; fi'
+  fi
+}
+
+# Read times in seconds from stdin, one number per line, echo each number
+# using format $1, and also echo the average transfer size in MB/s, its
+# standard deviation and the number of IOPS using the total I/O size $2 and
+# the block transfer size $3.
+echo_and_calc_avg() {
+  awk -v fmt="$1" -v iosize="$2" -v blocksize="$3" 'BEGIN{pow_2_20=1024*1024}{if ($1 != 0){n++;sum+=iosize/$1;sumsq+=iosize*iosize/($1*$1)};printf fmt, $1} END{d=(n>0?sumsq/n-sum*sum/n/n:0);avg=(n>0?sum/n:0);stddev=(d>0?sqrt(d):0);iops=avg/blocksize;printf fmt fmt fmt,avg/pow_2_20,stddev/pow_2_20,iops}'
+}
+
+time_write() {
+  if [ "${use_fio}" = "true" ]; then
+    if [ "${iotype}" = "direct" ]; then
+      fio_flags="--direct=1"
+    else
+      fio_flags="--direct=0 --end_fsync=1"
+    fi
+    fio  --rw=write --filename="${device}" --bs=$1 --size=$(($1*$2)) --ioengine=sync --end_fsync=1 --invalidate=1 ${fio_flags} --name=writeperftest \
+    | sed -n 's/.*runt= *\([0-9]*\)msec.*/\1/p' \
+    | awk '{print $1/1000}'
+  else
+    drop_caches
+    if [ "${iotype}" = "direct" ]; then
+      dd_oflags="oflag=direct conv=notrunc"
+    else
+      dd_oflags=""
+    fi
+    { dd if=/dev/zero of="${device}" bs=$1 count=$2 ${dd_oflags} 2>&1; sync; } \
+      | sed -n -e 's/.* \([0-9.]*\) s,.*/\1/p' | sed 's/^$/0/'
+  fi
+}
+
+time_read() {
+  if [ "${use_fio}" = "true" ]; then
+    if [ "${iotype}" = "direct" ]; then
+      fio_flags="--direct=1"
+    else
+      fio_flags="--direct=0"
+    fi
+    fio  --rw=read --filename="${device}" --bs=$1 --size=$(($1*$2)) --ioengine=sync --end_fsync=1 --invalidate=1 ${fio_flags} --name=readperftest \
+    | sed -n 's/.*runt= *\([0-9]*\)msec.*/\1/p' \
+    | awk '{print $1/1000}'
+  else
+    drop_caches
+    if [ "${iotype}" = "direct" ]; then
+      dd_iflags="iflag=direct"
+    else
+      dd_iflags=""
+    fi
+    dd if="${device}" of=/dev/null bs=$1 count=$2 ${dd_iflags} 2>&1 \
+      | sed -n -e 's/.* \([0-9.]*\) s,.*/\1/p' | sed 's/^$/0/'
+  fi
 }
 
 
@@ -45,10 +122,15 @@ function drop_caches {
 # Default settings      #
 #########################
 
+force=false
+iterations=3
 log2_io_size=30       # 1 GB
-log2_min_blocksize=12 # 4096 bytes
+log2_min_blocksize=9  # 512 bytes
 log2_max_blocksize=26 # 64 MB
 iotype=direct
+read_test_only=false
+target_login=""
+use_fio=false
 verify_device_data=true
 
 
@@ -56,14 +138,19 @@ verify_device_data=true
 # Argument processing   #
 #########################
 
-set -- $(/usr/bin/getopt "adns:" "$@")
+set -- $(/usr/bin/getopt "adfhi:jnrs:t:" "$@")
 while [ "$1" != "${1#-}" ]
 do
   case "$1" in
     '-a') iotype="buffered"; shift;;
     '-d') iotype="direct"; shift;;
+    '-f') force="true"; shift;;
+    '-i') iterations="$2"; shift; shift;;
+    '-j') use_fio=true; shift;;
     '-n') verify_device_data="false"; shift;;
+    '-r') read_test_only="true"; shift;;
     '-s') log2_io_size="$2"; shift; shift;;
+    '-t') target_login="$2"; shift; shift;;
     '--') shift;;
     *)    usage; exit 1;;
   esac
@@ -86,53 +173,98 @@ if [ ! -e "${device}" ]; then
   exit 1
 fi
 
-if [ ! -w "${device}" ]; then
+if [ "${read_test_only}" = "false" -a ! -w "${device}" ]; then
   echo "Error: device ${device} is not writeable."
   exit 1
 fi
 
-if [ "${verify_device_data}" = "true" ] \
-   && ! cmp -s -n $((2**log2_io_size)) "${device}" /dev/zero
+if [ $(dd if="${device}" bs=1M count=$(pow2 $(($log2_io_size - 20))) \
+     2>/dev/null | wc --bytes) -lt $(pow2 $log2_io_size) ]
+then
+  echo "Error: device ${device} contains less than $(pow2 $log2_io_size) bytes."
+  exit 1
+fi
+
+if [ "${read_test_only}" = "false" -a "${verify_device_data}" = "true" ] \
+   && [ "${force}" != "true" ] \
+   && ! cmp -s -n $(pow2 $log2_io_size) "${device}" /dev/zero
 then
   echo "Error: device ${device} still contains data."
   exit 1
 fi
 
-if [ "${iotype}" = "direct" ]; then
-  dd_oflags="oflag=direct"
-  dd_iflags="iflag=direct"
-else
-  dd_oflags="oflag=sync"
-  dd_iflags=""
+if ! can_drop_cache; then
+  echo ""
+  echo "WARNING: insufficient privileges to drop the file system cache"
+  echo "-- results will be unreliable."
+  echo ""
 fi
 
-printf "%9s %8s %8s %8s %8s %8s %8s\n" blocksize W W W R R R
+# Header, line 1
+printf "%9s " blocksize
+i=0
+while [ $i -lt ${iterations} ]
+do
+  printf "%8s " "W"
+  i=$((i+1))
+done
+printf "%8s %8s %8s " "W(avg," "W(std," "W"
+i=0
+while [ $i -lt ${iterations} ]
+do
+  printf "%8s " "R"
+  i=$((i+1))
+done
+printf "%8s %8s %8s" "R(avg," "R(std" "R"
+printf "\n"
 
-for ((log2_blocksize = log2_max_blocksize;
-      log2_blocksize >= log2_min_blocksize;
-      log2_blocksize--))
+# Header, line 2
+printf "%9s " "(bytes)"
+i=0
+while [ $i -lt ${iterations} ]
+do
+  printf "%8s " "(s)"
+  i=$((i+1))
+done
+printf "%8s %8s %8s " "MB/s)" ",MB/s)" "(IOPS)"
+i=0
+while [ $i -lt ${iterations} ]
+do
+  printf "%8s " "(s)"
+  i=$((i+1))
+done
+printf "%8s %8s %8s" "MB/s)" ",MB/s)" "(IOPS)"
+printf "\n"
+
+# Measurements
+log2_blocksize=${log2_max_blocksize}
+while [ ! $log2_blocksize -lt $log2_min_blocksize ]
 do
   if [ $log2_blocksize -gt $log2_io_size ]; then
+    log2_blocksize=$((log2_blocksize - 1))
     continue
   fi
-  bs=$((2**log2_blocksize))
-  count=$((2**(log2_io_size - log2_blocksize)))
+  iosize=$(pow2 $log2_io_size)
+  bs=$(pow2 $log2_blocksize)
+  count=$(pow2 $(($log2_io_size - $log2_blocksize)))
   printf "%9d " ${bs}
-  for ((i=0;i<3;i++))
+  i=0
+  while [ $i -lt ${iterations} ]
   do
-    drop_caches
-    elapsed="$(dd if=/dev/zero of="${device}" bs=${bs} count=${count} \
-                  ${dd_oflags} 2>&1 \
-               | sed -n 's/.* \([0-9.]*\) s,.*/\1/p')"
-    printf "%8s " "${elapsed}"
-  done
-  for ((i=0;i<3;i++))
+    if [ "${read_test_only}" = "false" ]; then
+      time_write ${bs} ${count}
+    else
+      echo " 0 s,"
+    fi
+    i=$((i+1))
+  done | echo_and_calc_avg "%8.3f " ${iosize} ${bs}
+
+  i=0
+  while [ $i -lt ${iterations} ]
   do
-    drop_caches
-    elapsed="$(dd if="${device}" of=/dev/null bs=${bs} count=${count} \
-                  ${dd_iflags} 2>&1 \
-               | sed -n 's/.* \([0-9.]*\) s,.*/\1/p')"
-    printf "%8s " "${elapsed}"
-  done
+    time_read ${bs} ${count}
+    i=$((i+1))
+  done | echo_and_calc_avg "%8.3f " ${iosize} ${bs}
   printf "\n"
+  log2_blocksize=$((log2_blocksize - 1))
 done
